pages:
  - name: Home
    file: index.html
    editable_areas:
      - selector: ".hero"
        type: text
        
  - name: Serviços
    file: servicos.html

  - name: Galeria
    file: galeria.html
    editable_areas:
      - selector: ".galeria img"
        type: image
